name: Application CI

on:
  push:
    branches:

concurrency:
  group: application-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  app:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.pull_request.title, '[skip ci]')
      && !contains(github.event.pull_request.title, '[ci skip]')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven
      - name: Run Tests
        run: ./mvnw verify
